workflows:
  ios:
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: 'Animaccess'
    environment:
      cocoapods: 1.10.2
      vars:
        BUNDLE_ID: 'com.gt.animaccess'
        XCODE_WORKSPACE: 'animaccess.xcworkspace' # <-- Name of your Xcode workspace
        XCODE_SCHEME: 'animaccess'
        APP_STORE_APPLE_ID: 6478528986
      ios_signing:
        provisioning_profiles:
          - AnimaccessProvisioningProfile
          # - ...
        certificates:
          - AnimaccessCertificat
    scripts:
      - name: Install dependencie
        script: |
          yarn install
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod deintegrate && pod install
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles --project ios/*.xcodeproj
      - name: show permission
        script: |
          chmod a+r $FCI_BUILD_DIR/ios/animaccess.xcworkspace
      - name: Increment build number
        script: |
          #!/bin/sh
          cd $CM_BUILD_DIR/ios
          ls
          agvtool new-version -all 9
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
          --workspace "$FCI_BUILD_DIR/ios/animaccess.xcworkspace" \
          --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        # Use referenced App Store Connect API key to authenticate binary upload
        auth: integration

        # Configuration related to TestFlight (optional)

        # Optional boolean, defaults to false. Whether or not to submit the uploaded
        # build to TestFlight beta review. Required for distributing to beta groups.
        # Note: This action is performed during post-processing.
        submit_to_testflight: true

        # Optional boolean, defaults to false. Set to true to automatically expire
        # previous build in review or waiting for review in Testflight before
        # submitting a new build to beta review. Expired builds will no longer be available for testers.
        # Note: This action is performed during post-processing.
        expire_build_submitted_for_review: true

        beta_groups:
          - Animaccess_tester

        # Configuration related to App Store (optional)

        # Optional boolean, defaults to false. Whether or not to submit the uploaded
        # build to App Store review. Note: This action is performed during post-processing.
        submit_to_app_store: true

        # Optional boolean, defaults to false. Set to true to cancel the previous
        # submission (if applicable) when submitting a new build to App Store review.
        # This allows automatically submitting a new build for review if a previous submission exists.
        # Note: This action is performed during post-processing.
        cancel_previous_submissions: true
