// common route
export const LOGIN = "Login"
export const SIGNUP = "SignUP"
export const SIGNUPSTEP2ETABLISSEMENT = "SignUP Step2 etablissement"
export const SIGNUPSTEP2PRESTATAIRE = "SignUp step2 prestataire"
export const FORGOT_PASSWORD = "Forgot password"
export const VALIDATE_OTP = "Validate otp"
export const RESET_PASSWORD = "Reset password"
export const WELCOME = "Welcome"
export const ETABLISSEMENT_NAVIGATOR = "Etablissement navigator"
export const PRESTATAIRE_NAVIGATOR = "Prestataire navigator"
export const PASSWORD_ETABLISSEMENT = "Password etablissement"
export const PASSWORD_PRESTATAIRE = "Password prestataire"
export const CHANGE_PASSWORD = "Change password"
export const EDIT_EMAIL = "Edit email"
export const EDIT_NAME = "Edit name"
export const EDIT_PHONE = "Edit phone"
export const EDIT_ETABLISSEMENT_NAME = "Edit etablissement name"
export const EDIT_TYPE_ETABLISSEMENT = "Edit type etablissement"

// prestataire route 
export const HOME_PRESTATAIRE = "Home prestataire"
export const EDIT_SERVICE = "Edit service"
export const CREATE_SERVICE = "Create service"
export const MYACCOUNT_PRESTATAIRE = "My account prestataire"
export const MY_SERVICE = "My service"
export const BOOKING_STACK = "Booking Stack"
export const MYBOOKING_PRESTATAIRE = "My booking prestataire"
export const SIGNUP_DOCUMENT = "SignUp document prestataire"
export const SERVICE_STACK = "Service stack navigator"
export const BOOKING_DETAIL_PRESTATAIRE = "booking detail prestataire"


// etablissement route
export const HOME_ETABLISSEMENT = "Home etablissement"
export const DETAIL_SERVICE = "Detail service"
export const FAVORITES = "Favorites"
export const MYACCOUNT_ETABLISSEMENT = "My account etablissement"
export const SEARCH = "Search"
export const SEARCH_BYCATEGORIE = "Search by categorie"
export const SEARCH_STACK = "Search stack navigator"
export const BOOKING_SERVICE = "Booking service"
export const BOOKING_DETAIL = "Booking detail"
export const MYACCOUNT_STACK = "My account stack navigator"